multiple-files: multiple-files.c extrafile.c extrafile.h
	cc -o multiple-files extrafile.c multiple-files.c
multiple-files-alt: multiple-files:c extrafile.c extrafile.h
	cc extrafile.c
	cc -o multiple-files multiple-files.c
